### ISSUE TITLE
Support ImGui viewports (multiple windows)

### ISSUE THREAD

**Issue by pkdawson** [pkdawson/imgui-godot#14]
https://github.com/ocornut/imgui/wiki/Multi-Viewports

https://docs.godotengine.org/en/latest/classes/class_window.html

The remaining work required seems to be converting between local (window) coordinates and global (screen) coordinates in the right places. Mouse input and rendering.

**Comment by arran-nz** [comment]
Here's a fun example:

GDScript, but may prove useful as Impl reference.

https://www.reddit.com/r/godot/comments/xr8yxn/learning_a_godot_40_window_node/
https://github.com/gongpha/godot4-window-test
