### ISSUE TITLE
Interface for C++ / GDExtension

### ISSUE THREAD

**Issue by pkdawson** [pkdawson/imgui-godot#18]
It's possible to also use ImGui from outside C# by sharing the context pointer and using the exact same version of ImGui. I should document this, and add a method for getting the current context. That could be done on ImGuiLayer, but I'll probably wait and use GDExtension instead, which should be available for C# soon.

I'd also like to provide an optional C++ implementation of the renderer, but viewports make that more complicated.

**Comment by EIREXE** [comment]
Hey, I made my own implementation of imgui in C++ based on the code from this repo, it currently doesn't work correctly in 4.1 (for reasons beyond my comprehension), but in 4.0 it works fine! https://github.com/EIRTeam/godot/tree/swansong/modules/imgui

See https://github.com/EIRTeam/godot/blob/swansong/modules/game/game_main_loop.cpp for initialization

unfortunately it currently doesn't support multiple viewports, haven't figured out a good way to do so just yet

**Comment by pkdawson** [comment]
@EIREXE Hey, nice work. Multi-viewports are definitely tricky, but they're doable with `Window` nodes.

I like having a pure C# addon so it's really simple for everyone to use and maintain. But I've thought about making an optional C++ GDExtension which would support simultaneous usage from C#, GDScript, C++, etc. I'll find some time to work on it, since I could use a better C++ interface too.

**Comment by pkdawson** [comment]
Implemented in v5.0.0
