### ISSUE TITLE
Possible to use Imgui GUI system in 3D Gui?

### ISSUE THREAD

**Issue by GeorgeS2019** [pkdawson/imgui-godot#41]
Wonder if this Imgui could be used in [3D Gui?](https://github.com/godotengine/godot-demo-projects/issues/979#issuecomment-1763063052)

**Comment by pkdawson** [comment]
Dear ImGui is not really intended to be used as a GUI for players (it has very limited support for custom themes), so this isn't something I've thought about.

If this is a feature you want, I can look into it, but generally I think Godot's own GUI system would be a better fit for 3D environments.
