### ISSUE TITLE
How do I get rid of menubar border?

### ISSUE THREAD

**Issue by Shadowblitz16** [pkdawson/imgui-godot#46]
How do I get rid of menubar border?
I tried pushing some style vars and colors and it doesn't disappear;

![image](https://github.com/pkdawson/imgui-godot/assets/2453707/fd0ab329-ee9c-4204-8685-c59e814ac510)

**Comment by pkdawson** [comment]
This is a question about general ImGui usage, which I have no special expertise or knowledge about.

But I think you want:
```csharp
ImGui.PushStyleVar(ImGuiStyleVar.WindowBorderSize, 0);
if (ImGui.BeginMainMenuBar())
{
    // ...
}
ImGui.PopStyleVar();
```
