### ISSUE TITLE
Image does no work with AtlasTextures and their Regions

### ISSUE THREAD

**Issue by critcap** [pkdawson/imgui-godot#49]
The Image widget appears not working correctly when using AtlasTextures. It will display the whole AtlasTexture and not just the specified region of the AtlasTexture e.g. The whole TileSet is shown instead of the a single tile.

**Comment by maidopi-usa** [comment]
Maybe a workaround...you could additionally use `AtlasTexture.Region.Position / AtlasTexture.Atlas.GetSize()` as parameter `uv0`,  and `AtlasTexture.Region.End / AtlasTexture.Atlas.GetSize()` as parameter `uv1`  on `Widgets.Image()` or `Widgets.ImageButton()` for displaying regions correctly

**Comment by pkdawson** [comment]
This is a good feature I hadn't thought of. I'll add methods which take an `AtlasTexture` and set the UV parameters.

**Comment by pkdawson** [comment]
Added in v4.1.0
