### ISSUE TITLE
ImGui rendering glitches on Godot 4.3/Vulkan Backend

### ISSUE THREAD

**Issue by maidopi-usagi** [pkdawson/imgui-godot#50]
<img width="650" alt="image" src="https://github.com/pkdawson/imgui-godot/assets/33864304/ff16c0b4-9514-4769-a913-70a19cc5ff1e">

Steps to reproduce: just directly open imgui-godot demo project with official Godot v4.3dev1, and with rendering method in project settings set to "forward_plus".
When rendering method is set to "compatibility", everything works well.

**Comment by pkdawson** [comment]
Yeah Godot's `RenderingDevice` refactor broke something. There's a recently merged PR which *might* fix this, but if not I plan to investigate this myself next week.

**Comment by pkdawson** [comment]
Confirmed this is still broken in the current Godot git. I'll make sure this gets fixed one way or another before 4.3 stable, but hopefully sooner than that.

**Comment by pkdawson** [comment]
[The fix](https://github.com/godotengine/godot/pull/86852) was merged, and imgui-godot works normally in Godot 4.3-dev2.
