### ISSUE TITLE
Upload to AssetLib

### ISSUE THREAD

**Issue by m21-cerutti** [pkdawson/imgui-godot#57]
Hello,

Would it be possible to upload it to AssetLib ?
Even if it's simple to install, would be maybe more interesting to have it on AssetLib if no technical problem prevent it (however I don't know how it will work with GDExtensions).

![image](https://github.com/pkdawson/imgui-godot/assets/23432929/11e6872e-a962-449e-a330-2cf8b08da7f1)

**Comment by pkdawson** [comment]
I've thought about this a few times, including just today actually. I'm definitely planning to be on the new Asset Store, whenever that's available.

There are a few minor hurdles, but my main concern is that installing this plugin in a C# project requires a few extra manual steps (allow unsafe code, install ImGui.NET). So if you just click install without reading carefully, you see a bunch of confusing errors. Maybe I could add a message box or something.

OK, I'll submit this to the Asset Library after I release v5.1.0

**Comment by pkdawson** [comment]
Done!

https://godotengine.org/asset-library/asset/2985
