### ISSUE TITLE
ImGui updated to v1.91.0

### ISSUE THREAD

**Issue by mrawlingst** [pkdawson/imgui-godot#76]
Ocornut has released a new major update for ImGui - v1.91.0

Release notes: https://github.com/ocornut/imgui/releases/tag/v1.91.0

Currently this addon runs on v1.90.9.

 I already updated my version of addon to use 1.91.0 but it's not fully compatible yet especially with some new widgets i.e. `TextLink()`.

**Comment by pkdawson** [comment]
Released in v6.2.0

TextLink works as expected by default (tested on Windows and macOS), but let me know if you have any trouble.

https://github.com/pkdawson/imgui-godot/blob/a461bf47163ac6459664d5f9431375647982cc20/doc/examples/GdsDemo/demo.gd#L36
