### ISSUE TITLE
addon make project crash on double precision Builds

### ISSUE THREAD

**Issue by skami48** [pkdawson/imgui-godot#77]
When you build godot from source to enable double precision, adding the addon make the project Crashes  on single presicion build the addon works fine.

**Comment by pkdawson** [comment]
That's expected, the GDExtension is built with the default single precision.

> GDExtension add-ons are also only compatible with engine builds that use the level of floating-point precision the extension was compiled for. This means that if you use a engine build with double-precision floats, the extension must also be compiled for double-precision floats.

https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/what_is_gdextension.html#version-compatibility

I'll add a double precision build, but it requires some nontrivial changes, so it may take a little while.

**Comment by pkdawson** [comment]
A double precision build is now included in the release files.
