### ISSUE TITLE
Errors when compiling - 4.2.2stable C#

### ISSUE THREAD

**Issue by 8xc0a** [pkdawson/imgui-godot#78]
after reinstalling the plugin and adding /unsafe command blocks to the solution i get this when compiling:

![Godot_v4 2 2-stable_mono_win64_OM2UkFV2lV](https://github.com/user-attachments/assets/87fa7068-d273-482d-a8aa-a68aaf3e745c)

any solution to this problem?

**Comment by pkdawson** [comment]
You probably need to target .NET 8

https://github.com/pkdawson/imgui-godot/blob/1fd003e39058ca4616b16cf47c0bf663c8813bd0/Dear%20ImGui%20for%20Godot%20Demo.csproj#L2-L3

**Comment by 8xc0a** [comment]
thanks, it works
