### ISSUE TITLE
Minimizing a window crashes the game when using tables

### ISSUE THREAD

**Issue by Burloe** [pkdawson/imgui-godot#86]
First off, this might very well be a user error and apologies if that's the case. First time user and just trying it out but I created a window with 4 tables in order to display some basic information. The info displayed is just some basic variable values and particle properties in an autoload called "EnvironmentManager" which handles weather, canvas modulate, dates, time etc. All data displays properly but trying to minimize the window, instantly crashes the game. I've tried to turn every element combination I could off and on to see any outliers but as soon as `if ImGui.BeginTable("Environments:", dates.size() + 1, table_flags):` and any subsequent table call is made, I can't use the minimize button.

Here's the code(which is in the EnvironmentManager script):
```gdscript
func _process(delta):
	ImGui.Begin("EnvironmentManager")
	ImGui_set_table(0)
	ImGui.EndTable()
	ImGui_set_table(1)
	ImGui.EndTable()
	ImGui_set_table(2)
	ImGui.EndTable()
	ImGui.Text(str("\nVariationTimer: ", variation_timer.get_time_left()))
	ImGui.Text(str("WindTimer: ", wind_timer.get_time_left()))
	ImGui.Text(str("ThunderTimer: ", thunder_timer.get_time_left()))
	ImGui.End()


func ImGui_set_table(table : int):
	var table_flags = ImGui.TableFlags_BordersOuter |ImGui.TableFlags_BordersInner
	match table:
		0:
			ImGui.Text("Environments:")
			ImGui.Text("    Weathers: 0 = Sunny   1 = Cloudy   2 = Overcast   3 = Storm")
			ImGui.Text("    WeatherFX: 0 = None   1 = Leafy    2 = Rainy      3 = Randomized(Leaf/Rain)\n\n")
			## Using above code plus code from here ##
			if ImGui.BeginTable("Environments:", dates.size() + 1, table_flags): # Not using table_flags changes nothing
				ImGui.TableNextColumn()
				ImGui.Text("Date")                                      
			## To here will cause the crashing ##
				ImGui.TableNextColumn()
				ImGui.Text("Weather")
				ImGui.TableNextColumn()
				ImGui.Text("WeatherFX")
				ImGui.TableNextColumn()
				ImGui.Text("Wind")
				ImGui.TableNextColumn()
				ImGui.Text("Thunder")
				ImGui.TableNextColumn()
				ImGui.Text("CanvasColors")
				ImGui.TableNextRow()
				for i in range(dates.size()):
					ImGui.TableNextColumn()
					ImGui.Text(str(dates[i].date_id)) # int
					ImGui.TableNextColumn()
					ImGui.Text(str(dates[i].weather)) # int
					ImGui.TableNextColumn()
					ImGui.Text(str(dates[i].weatherfx)) # int
					ImGui.TableNextColumn()
					ImGui.Text(str(dates[i].wind)) # bool
					ImGui.TableNextColumn()
					ImGui.Text(str(dates[i].thunder)) # bool
					ImGui.TableNextColumn()
					if dates[i].canvasmod_overrides.size() != 0: # Array[Color]
						ImGui.Text("True")
					else: ImGui.Text("False")
				# Only including this table since all of them independently causes crashes but there are three more.  
``` 
![image](https://github.com/user-attachments/assets/ab03ebbf-e0bb-475e-b18e-fb3f12442c54)

**Comment by pkdawson** [comment]
`EndTable` should only be called if `BeginTable` returns true. See https://github.com/pkdawson/imgui-godot/issues/63#issuecomment-2144091650

You might see a message like this in your terminal window just before the crash:
```
ERROR: IM_ASSERT table != NULL && "Only call EndTable() if BeginTable() returns true!" (imgui\imgui_tables.cpp:1322)
```

> this might very well be a user error and apologies if that's the case

No worries, I don't mind the occasional question about ImGui usage.

**Comment by Burloe** [comment]
Oh, I see. I moved them into the `if ImGui.BeginTable():` and now it works properly.  
> No worries, I don't mind the occasional question about ImGui usage.

Great, thank you for the help! I'll go ahead and close this.
