### ISSUE TITLE
Plugin doesn't work without C#?

### ISSUE THREAD

**Issue by JekSun97** [pkdawson/imgui-godot#94]
I remember the old version worked fine on 4.2 without C#, now I don't see any ImGui element in Godot 4.3

![123](https://github.com/user-attachments/assets/e5099f2a-d1d1-414f-8fff-1952e9f6d63c)

**Comment by JekSun97** [comment]
@pkdawson

**Comment by pkdawson** [comment]
The main demo project has always required C#. If you need GDScript examples, see doc/examples.
